name:                hlive-1h
version:             0.1.0.0
github:              "Kot-Dymok/hlive-1h"
license:             BSD3
author:              "Kot Dymok"
maintainer:          "kot.dymok+git@gmail.com"
copyright:           "© 2019 Kot Dymok"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Game

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Kot-Dymok/hlive-1h#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hlive-1h-exe:
    main:                Main.hs
    source-dirs:         lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlive-1h

tests:
  hlive-1h-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlive-1h
